import { Product } from "../product";

export const Products: Product[] = [
{
  id: 1,
  name: "Burberry",
  brand:1,
  type: 5,
  size: 1,
  description :"very stylish and upto the mark product.",
  url : "assets/Products/product_burberry1.PNG",
  amount : 2800,
  season : "winter",
  additionalInfo : "",
  discount : 20
},
{
  id: 2,
  name: "Cauch",
  brand:2,
  type: 5,
  size :2,
  description :"very stylish and upto the mark product.",
  url : "assets/Products/product_cauch1.PNG",
  amount : 3600,
  season : "winter",
  additionalInfo : "",
  discount : 20
},
{
  id: 3,
  name: "Cauch",
  brand:2,
  type: 5,
  size: 1,
  description :"very stylish and upto the mark product.",
  url : "assets/Products/product_cauch2.PNG",
  amount : 3600,
  season : "winter",
  additionalInfo : "",
  discount : 20
},
{
  id: 4,
  name: "Cauch",
  brand:2,
  type: 5,
  size: 1,
  description :"very stylish and upto the mark product.",
  url : "assets/Products/product_cauch3.PNG",
  amount : 3600,
  season : "winter",
  additionalInfo : "trandy",
  discount : 20
},
{
  id: 5,
  name: "Cauch",
  brand:2,
  type: 5,
  size: 3,
  description :"very stylish and upto the mark product.",
  url : "assets/Products/product_cauch4.PNG",
  amount : 3600,
  season : "winter",
  additionalInfo : "",
  discount : 20
},
{
  id: 6,
  name: "Chanel",
  type: 1,
  brand:3,
  size: 2,
  description :"very stylish and upto the mark product.",
  url : "assets/Products/product_chanel1.PNG",
  amount : 2500,
  season : "winter",
  additionalInfo : "",
  discount : 20
},
{
  id: 7,
  name: "Chloe",
  brand:4,
  type: 1,
  size:3,
  description :"Maeve Large Logo Tote Bag.",
  url : "assets/Products/product_chloe1.PNG",
  amount : 2800,
  season : "winter",
  additionalInfo : "",
  discount : 20
},
{
  id: 8,
  name: "Christian Dior",
  brand:5,
  type: 3,
  size:2,
  description :"Maeve Large Logo Tote Bag.",
  url : "assets/Products/product_christian_dior1.PNG",
  amount : 2800,
  season : "winter",
  additionalInfo : "",
  discount : 20
},
{
  id: 9,
  name: "Christian Dior",
  brand:5,
  type: 1,
  size:2,
  description :"Maeve Large Logo Tote Bag.",
  url : "assets/Products/product_christian_dior2.PNG",
  amount : 2800,
  season : "winter",
  additionalInfo : "trandy",
  discount : 20
},
{
  id: 10,
  name: "Diesel",
  brand:6,
  type: 1,
  size:3,
  description :"Maeve Large Logo Tote Bag.",
  url : "assets/Products/product_diesel1.PNG",
  amount : 2800,
  season : "winter",
  additionalInfo : "",
  discount : 20
},
{
  id: 11,
  name: "Diesel",
  brand:6,
  type: 4,
  size:1,
  description :"Maeve Large Logo Tote Bag.",
  url : "assets/Products/product_diesel2.PNG",
  amount : 2800,
  season : "winter",
  additionalInfo : "",
  discount : 20
},
{
  id: 12,
  name: "Gucci",
  brand:7,
  type: 4,
  size:1,
  description :"Maeve Large Logo Tote Bag.",
  url : "assets/Products/product_gucci.png",
  amount : 2800,
  season : "winter",
  additionalInfo : "",
  discount : 20
},
{
  id: 13,
  name: "Gucci",
  brand:7,
  type: 1,
  size:4,
  description :"Maeve Large Logo Tote Bag.",
  url : "assets/Products/product_gucci1.PNG",
  amount : 2800,
  season : "winter",
  additionalInfo : "trandy",
  discount : 20
},
{
  id: 14,
  name: "Gucci",
  brand:7,
  type: 1,
  size:3,
  description :"Maeve Large Logo Tote Bag.",
  url : "assets/Products/product_gucci2.PNG",
  amount : 2800,
  season : "winter",
  additionalInfo : "",
  discount : 20
},
{
  id: 15,
  name: "Gucci",
  brand:7,
  type: 1,
  size:4,
  description :"Maeve Large Logo Tote Bag.",
  url : "assets/Products/product_gucci3.PNG",
  amount : 2800,
  season : "winter",
  additionalInfo : "",
  discount : 20
},
{
  id: 16,
  name: "Gucci",
  brand:7,
  type: 1,
  size:3,
  description :"Maeve Large Logo Tote Bag.",
  url : "assets/Products/product_gucci5.PNG",
  amount : 2800,
  season : "winter",
  additionalInfo : "",
  discount : 20
},
{
  id: 17,
  name: "Karl Lagerfeld",
  brand:8,
  type: 1,
  size:3,
  description :"Maeve Large Logo Tote Bag.",
  url : "assets/Products/product_karl_lagerfeld01.PNG",
  amount : 2800,
  season : "winter",
  additionalInfo : "",
  discount : 20
},
{
  id: 18,
  name: "Karl Lagerfeld",
  brand:8,
  type: 1,
  size:2,
  description :"Maeve Large Logo Tote Bag.",
  url : "assets/Products/product_karl_lagerfeld2.PNG",
  amount : 2800,
  season : "winter",
  additionalInfo : "",
  discount : 20
},
{
  id: 19,
  name: "Karl Lagerfeld",
  brand:8,
  type: 1,
  size:3,
  description :"Maeve Large Logo Tote Bag.",
  url : "assets/Products/product_karl_lagerfeld3.PNG",
  amount : 2800,
  season : "winter",
  additionalInfo : "trandy",
  discount : 20
},
{
  id: 20,
  name: "Louis Vuitton",
  brand:9,
  type: 1,
  size:1,
  description :"Trunk Bag.",
  url : "assets/Products/product_louis_Vuitton_TrunkBag.PNG",
  amount : 2800,
  season : "winter",
  additionalInfo : "",
  discount : 20
},
{
  id: 21,
  name: "Louis Vuitton",
  brand:9,
  type: 3,
  size:1,
  description :"Trunk Bag.",
  url : "assets/Products/product_louis_Vuitton01.PNG",
  amount : 2800,
  season : "winter",
  additionalInfo : "",
  discount : 20
},
{
  id: 22,
  name: "Louis Vuitton",
  brand:9,
  type: 3,
  size:1,
  description :"Trunk Bag.",
  url : "assets/Products/product_louis_Vuitton1.PNG",
  amount : 2800,
  season : "winter",
  additionalInfo : "",
  discount : 20
},
{
  id: 23,
  name: "Mark Jacobb",
  brand:10,
  type: 3,
  size:3,
  description :"Tote Bag.",
  url : "assets/Products/product_mark_jacobb_totebag.PNG",
  amount : 2800,
  season : "winter",
  additionalInfo : "",
  discount : 20
},
{
  id: 24,
  name: "Mark Jacobb",
  brand:10,
  type: 3,
  size:3,
  description :"small Bag.",
  url : "assets/Products/product_mark_jacobb01.PNG",
  amount : 2800,
  season : "winter",
  additionalInfo : "",
  discount : 20
},
{
  id: 25,
  name: "Michael Kors",
  brand:11,
  type: 3,
  size:2,
  description :"small Bag.",
  url : "assets/Products/product_mk1.png",
  amount : 2800,
  season : "winter",
  additionalInfo : "",
  discount : 20
},
{
  id: 26,
  name: "Michael Kors",
  brand:11,
  type: 3,
  size:1,
  description :"small Bag.",
  url : "assets/Products/product_mk2.png",
  amount : 2800,
  season : "winter",
  additionalInfo : "",
  discount : 20
},
{
  id: 27,
  name: "Michael Kors",
  brand:11,
  type: 3,
  size:4,
  description :"small Bag.",
  url : "assets/Products/product_mk3.PNG",
  amount : 2800,
  season : "winter",
  additionalInfo : "",
  discount : 20
},
{
  id: 28,
  name: "Michael Kors",
  brand:11,
  type: 3,
  size:4,
  description :"small Bag.",
  url : "assets/Products/product_mk4.PNG",
  amount : 2800,
  season : "winter",
  additionalInfo : "",
  discount : 20
},
{
  id: 29,
  name: "Michael Kors",
  brand:11,
  type: 3,
  size:4,
  description :"small Bag.",
  url : "assets/Products/product_mk5.PNG",
  amount : 2800,
  season : "winter",
  additionalInfo : "",
  discount : 20
},
{
  id: 30,
  name: "Michael Kors",
  brand:11,
  type: 3,
  size:1,
  description :"small Bag.",
  url : "assets/Products/product_mk6.PNG",
  amount : 2800,
  season : "winter",
  additionalInfo : "",
  discount : 20
},
{
  id: 31,
  name: "Michael Kors",
  brand:11,
  type: 3,
  size:1,
  description :"small Bag.",
  url : "assets/Products/product_mk7.PNG",
  amount : 2800,
  season : "winter",
  additionalInfo : "",
  discount : 20
},
{
  id: 32,
  name: "Michael Kors",
  brand:11,
  type: 3,
  size:4,
  description :"small Bag.",
  url : "assets/Products/product_mk8.PNG",
  amount : 2800,
  season : "winter",
  additionalInfo : "",
  discount : 20
},
{
  id: 33,
  name: "Michael Kors",
  brand:11,
  type: 3,
  size:3,
  description :"small Bag.",
  url : "assets/Products/product_mk9.PNG",
  amount : 2800,
  season : "winter",
  additionalInfo : "",
  discount : 20
},
{
  id: 34,
  name: "Michael Kors",
  brand:11,
  type: 3,
  size:4,
  description :"big Bag.",
  url : "assets/Products/product_mk10.PNG",
  amount : 2800,
  season : "winter",
  additionalInfo : "",
  discount : 20
},
{
  id: 35,
  name: "Michael Kors",
  brand:11,
  type: 3,
  size:4,
  description :"small Bag.",
  url : "assets/Products/product_mk11.PNG",
  amount : 2800,
  season : "winter",
  additionalInfo : "",
  discount : 20
},
{
  id: 36,
  name: "Michael Kors",
  brand:11,
  type: 3,
  size:2,
  description :"small Bag.",
  url : "assets/Products/product_mk12.PNG",
  amount : 2800,
  season : "winter",
  additionalInfo : "",
  discount : 20
},
{
  id: 37,
  name: "Michael Kors",
  brand:11,
  type: 3,
  size:4,
  description :"small Bag.",
  url : "assets/Products/product_mk13.PNG",
  amount : 2800,
  season : "winter",
  additionalInfo : "",
  discount : 20
},
{
  id: 38,
  name: "Prada Milano",
  brand:12,
  type: 3,
  size:1,
  description :"small Bag.",
  url : "assets/Products/product_prada_milano.PNG",
  amount : 2800,
  season : "winter",
  additionalInfo : "",
  discount : 20
},
{
  id: 39,
  name: "Prada Milano",
  brand:12,
  type: 3,
  size:1,
  description :"small Bag.",
  url : "assets/Products/product_prada1.PNG",
  amount : 2800,
  season : "winter",
  additionalInfo : "",
  discount : 20
},
{
  id: 40,
  name: "Versace",
  brand:12,
  type: 3,
  size:1,
  description :"small Bag.",
  url : "assets/Products/product_versace1.PNG",
  amount : 2800,
  season : "winter",
  additionalInfo : "",
  discount : 20
},
{
  id: 41,
  name: "Yues Saint Laurent",
  brand:14,
  type: 6,
  size:1,
  description :"small Bag.",
  url : "assets/Products/product_yues_saint_laurent.PNG",
  amount : 2800,
  season : "winter",
  additionalInfo : "",
  discount : 20
},

];